// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cusror_ai/internal/config"
	"cusror_ai/internal/controllers"
	"cusror_ai/internal/repositories"
	"cusror_ai/internal/services"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, error) {
	db, err := config.NewDatabaseConnection(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	app := &App{
		UserController: userController,
	}
	return app, nil
}

// wire.go:

type App struct {
	UserController *controllers.UserController
}
